config/routes.rb
Orient::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :user_types

  resources :home do
    collection do
      get 'toggle_email_notifications'
    end
  end

  match '/home_activities' => "home#activities", :method => :get
  match '/subscriber_activities' => "home#subscriber_activities", :method => :get
  match '/notifications' => "home#notifications", :method => :get
  match '/user_activities' => "home#user_activities", :method => :get

  resources :roles

  resources :comments do
    member do
      get 'load_more_comments'
    end
  end

  resources :search

  resources :areas do
    collection do
      get "search"
    end
  end

  resources :announcements do
    collection do
      get 'update_user_status'
    end
  end

  resources :product_categories do
    resources :svrs
  end

  resources :activities do
    member do
      get 'destroy_subscriber'
    end
    collection do
      get 'update_activity'
      post 'create_subscriber'
    end
  end

  resources :dealers do
   resources :images
   resources :shops
    member do
      get 'gallery'
      get 'showmodal'
      get 'get_info'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'showgallery'
      get 'area_field'
      get 'load_more_peoples'
      get 'load_more_dealers'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end

  end

  resources :brands do
    resources :svrs
  end

  resources :products do
    resources :svrs
  end

  resources :shop_categories do
    resources :shops
  end

  resources :cities do
    resources :shops
  end

  resources :locations do
    resources :shops
  end

  resources :images do
    member do
      post 'create_comment'
      get 'view_more_comments'
    end
  end

  resources :shops do
    resources :uploads
    resources :images
    resources :svrs do
      member do
        get "delete"
        get "comments"
        get "view_more_comments"
        post 'create_comment'
      end
    end

    member do
      get 'delete'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'area_field'
      get 'people_field'
      get 'load_more_peoples'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end
  end

  resources :uploads do
   member do
    post 'create_comment'
   end
  end

  resources :tasks do
    member do
      post 'change_status'
    end
    collection do
      get 'publish_report'
      get 'unpublish_report'
      get 'draft_report'
      get 'submit_report'
    end
  end

  resources :svrs do
    collection do
      post 'brand_search'
      post 'category_search'
      get  'file_field'
      get 'upload_field'
    end
  end

  match 'shops/:shop_id/svr/:id' => 'svrs#show', as: 'show'

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'home#index'

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  include PublicActivity::Common
  attr_accessible :announcement

  after_save :update_user

  def update_user
  	User.all.each do |user|
  		user.update_attributes(:view_announcement => true)
  	end
  end
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
	
	def index
		authorize! :read, Announcement
		@announcements = Announcement.order("created_at desc")
	end

	def show
		authorize! :read, Announcement
		@announcement =  Announcement.find(params[:id])
	end

	def new
		authorize! :create, Announcement
		@announcement =  Announcement.new
	end

	def edit
		authorize! :update, Announcement
		@announcement =  Announcement.find(params[:id])
	end

	def create
		@announcement =  Announcement.new(params[:announcement])
		respond_to do |format|
      if @announcement.save
        @announcement.create_activity :create, owner: current_user
        format.html { redirect_to @announcement, notice: 'Announcement was successfully created.' }
        format.json { render json: @announcement, status: :created, location: @announcement }
      else
        format.html { render action: "new" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
	end

	def update
		@announcement =  Announcement.find(params[:id])
		respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        @announcement.create_activity :update, owner: current_user
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
	end

	def destroy
		@announcement =  Announcement.find(params[:id])
		@announcement.create_activity :destroy, owner: current_user
		@announcement.destroy
		respond_to do |format|
    		format.html { redirect_to announcements_url, notice: 'Announcement was successfully deleted.'  }
    		format.json { head :no_content }
  	end
	end

	def update_user_status
		user = current_user
		user.update_attributes(:view_announcement => false)
		render :text => "successful"
	end

end

app/helpers/announcement_helper.rb
module AnnouncementHelper
end

app/views/announcements/_form.html.erb
<%= form_for @announcement, :html => {:class => 'form-horizontal form-bordered', :id => "form-validation" } do |f| %>
  <div class= "form-group error-box">
    <p><%= errors_for(@announcement, "").html_safe %></p>
  </div>
  <div class="form-group">
    <%= f.label :announcement, :class => ' col-md-2 control-label' %>
    <div class="col-md-9">
      <%= f.text_field :announcement, :class => 'form-control text_field required' %>
    </div>
  </div>

  <div class="form-group form-actions text-center">
    <%= f.button raw("<i class='fa fa-angle-right'></i> Submit"), :class => 'btn btn-sm btn-success' %>
    <%= link_to raw("<i class='fa fa-angle-left'></i> Back"), announcements_path, :class => 'btn btn-sm btn-primary' %>              
  </div>
<% end %>

app/views/announcements/edit.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="block">
		  <div class="block-title">
		   	<h2><strong>Edit Announcement </strong></h2>
		  </div>  
		  <%= render :partial => 'form' %>
		</div>
	</div>		
</div>	

app/views/announcements/index.html.erb
<div class="block">
  <div class="block-title">
    <h2><strong>Announcement </strong></h2>
    <% if can? :create, Announcement %> 
      <div class="new-button pull-right">
        <%= link_to raw("<i class='gi gi-new_window_alt'></i> Add Announcement"), new_announcement_path,  :class => "btn btn-large btn-default" %>
      </div>
    <% end %> 
  </div>

  <div class="table-responsive">
    <table class="table table-striped table-vcenter">
      <thead>
        <tr>
          <th>Announcement</th>
          <th>Create at </th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @announcements.each do |announcement| %>
          <tr>
            <td><%= link_to announcement.announcement, announcement_path(announcement) %></td>
            <td><%= announcement.created_at.strftime("%d %B, %Y %H:%M %p") %></td>
            <td>
              <div class="btn-group btn-group-xs">
                    <%= link_to raw("<i class='fa fa-pencil'></i>"),edit_announcement_path(announcement), :class => 'btn btn-default', "data-toggle" => "tooltip", :title=> "Edit" %>
                    <%= link_to raw("<i class='fa fa-times'></i>"),announcement_path(announcement),:method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), "data-toggle"=>"tooltip" ,:title=>"Delete" }, :class => 'btn btn-danger' %>
                  </div
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>    

app/views/announcements/new.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="block">
		  <div class="block-title">
		   	<h2><strong>Add Announcement </strong></h2>
		  </div>  
		  <%= render :partial => 'form' %>
		</div>
	</div>		
</div>	

app/views/announcements/show.html.erb
<div class="block">
  <div class="block-title">
    <h2><strong>Announcement </strong></h2>
    <div class="pull-right btn-group btn-group-xs"><%= link_to raw("<i class='gi gi-new_window'></i>"),new_announcement_path,:class => 'btn btn-default btn-new text-center ',"data-toggle" => "tooltip", :title=> "Add New"  %>
    </div>  
  </div>

  <dl class="dl-horizontal">
    <dt><strong>Name :</strong></dt>
    <dd><%= @announcement.announcement %></dd>
  </dl>

  <div class="form-group form-actions text-center btn-group-xs">
    <%= link_to raw("<i class='hi hi-arrow-left'></i>"),announcements_path,:class => 'btn btn-default text-center ',"data-toggle" => "tooltip", :title=> "Back"  %>
     <%= link_to raw("<i class='fa fa-pencil'></i>"),edit_announcement_path(@announcement), :class => 'btn btn-default', "data-toggle" => "tooltip", :title=> "Edit" %>
                <%= link_to raw("<i class='fa fa-times'></i>"),announcement_path(@announcement),:method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')), "data-toggle"=>"tooltip" ,:title=>"Delete" }, :class => 'btn btn-danger' %>
  </div>
</div>