config/routes.rb
Orient::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :user_types

  resources :home do
    collection do
      get 'toggle_email_notifications'
    end
  end

  match '/home_activities' => "home#activities", :method => :get
  match '/subscriber_activities' => "home#subscriber_activities", :method => :get
  match '/notifications' => "home#notifications", :method => :get
  match '/user_activities' => "home#user_activities", :method => :get

  resources :roles

  resources :comments do
    member do
      get 'load_more_comments'
    end
  end

  resources :search

  resources :areas do
    collection do
      get "search"
    end
  end

  resources :announcements do
    collection do
      get 'update_user_status'
    end
  end

  resources :product_categories do
    resources :svrs
  end

  resources :activities do
    member do
      get 'destroy_subscriber'
    end
    collection do
      get 'update_activity'
      post 'create_subscriber'
    end
  end

  resources :dealers do
   resources :images
   resources :shops
    member do
      get 'gallery'
      get 'showmodal'
      get 'get_info'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'showgallery'
      get 'area_field'
      get 'load_more_peoples'
      get 'load_more_dealers'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end

  end

  resources :brands do
    resources :svrs
  end

  resources :products do
    resources :svrs
  end

  resources :shop_categories do
    resources :shops
  end

  resources :cities do
    resources :shops
  end

  resources :locations do
    resources :shops
  end

  resources :images do
    member do
      post 'create_comment'
      get 'view_more_comments'
    end
  end

  resources :shops do
    resources :uploads
    resources :images
    resources :svrs do
      member do
        get "delete"
        get "comments"
        get "view_more_comments"
        post 'create_comment'
      end
    end

    member do
      get 'delete'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'area_field'
      get 'people_field'
      get 'load_more_peoples'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end
  end

  resources :uploads do
   member do
    post 'create_comment'
   end
  end

  resources :tasks do
    member do
      post 'change_status'
    end
    collection do
      get 'publish_report'
      get 'unpublish_report'
      get 'draft_report'
      get 'submit_report'
    end
  end

  resources :svrs do
    collection do
      post 'brand_search'
      post 'category_search'
      get  'file_field'
      get 'upload_field'
    end
  end

  match 'shops/:shop_id/svr/:id' => 'svrs#show', as: 'show'

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'home#index'

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController


  def index
    page = params[:page].nil? ? 1: params[:page]
    if params[:filter].present?
      search = Sunspot.search(Shop) do
        with(:city_id, params[:filter][:city_id]) if params[:filter][:city_id].present?
        with(:area_id, params[:filter][:area_id]) if params[:filter][:area_id].present?
        with(:shop_category_id, params[:filter][:shop_category_id]) if params[:filter][:shop_category_id].present?
      end
      from = params[:filter][:from].present? ? ((params[:filter][:from]).to_date).to_time : Post.first.created_at.to_date.to_time
      to = params[:filter][:to].present? ? ((params[:filter][:to]).to_date).to_time : Date.today.to_date.to_time

      @shops = search.results
      shop_ids = flatten_data(@shops, &:id)
      @limited_shops =  apply_array_pagination(@shops,params[:page])
      @shop_categories = flatten_data(@shops, &:shop_category)
      @peoples = apply_array_pagination(flatten_data(@shops, &:peoples), 1)
      @posts = Post.with_shops(shop_ids).where('created_at >= ? AND created_at <= ?',from, to)
      post_ids = flatten_data(@posts,&:id)
      @reports = Report.with_posts(post_ids)
      report_ids = flatten_data(@reports,&:id)
      @corner_reports  = apply_array_pagination(ReportLine.with_reports(report_ids), 1)
      @corner_brand_report_lines = @corner_reports.group_by {|d| d[:brand_id] }
      @corner_category_report_lines = @corner_reports.group_by {|d| d[:product_category_id]}
      @categories= flatten_data(@posts,&:product_category).uniq
      @brands = flatten_data(@categories,&:brands).uniq
      @uploads = apply_array_pagination((Upload.with_shops(shop_ids) + Upload.with_posts(post_ids)), 1)
    else
      @limited_shops = Shop.page(params[:page]).per(10)
      @shops = Shop.all
      @shop_categories = ShopCategory.all
      @posts = Post.published_reports
      @peoples = People.page(1).per(10)
      if @posts.present?
        @reports = flatten_data(@posts,&:reports)
        report_ids = flatten_data(@reports,&:id)
        @corner_reports = apply_array_pagination(ReportLine.with_reports(report_ids), 1)
        @corner_brand_report_lines = @corner_reports.group_by {|d| d[:brand_id] }
        @corner_category_report_lines = @corner_reports.group_by {|d| d[:product_category_id]}

        @categories= flatten_data(@posts,&:product_category).uniq
        @brands = flatten_data(@categories,&:brands).uniq
        @uploads = Upload.page(1).per(10)
      end
    end
    respond_to do |format|
      format.html
      format.js
      format.json
    end
  end

  def load_more_shops
    page = params[:page].nil? ? 1 : params[:page]
    if params[:filter].present?
      search = Sunspot.search (Shop) do
        keywords params[:dealer_name] do
          fields(:dealer_name)
        end
        with(:city_id, params[:filter][:city_id]) if params[:filter][:city_id].present?
        with(:area_id, params[:filter][:area_id]) if params[:filter][:area_id].present?
        with(:shop_category_id, params[:filter][:shop_category_id]) if params[:filter][:shop_category_id].present?
      end
      @limited_shops = apply_array_pagination(search.results,params[:page])
    else
      unless params[:dealer_name].blank?
        search = Sunspot.search(Shop) do
          keywords params[:dealer_name] do
            fields(:dealer_name)
          end
        end
        @limited_shops = apply_array_pagination(search.results,page)
      else
        @limited_shops = Shop.page(page).per(10)
      end
    end
    respond_to do |format|
      format.js
    end
  end

  def load_more_peoples
    @peoples = load_filter_peoples
    render :partial => '/shops/more_peoples', :layout => false
  end

  def load_more_brand_corner_report_lines
    @corner_reports = load_filtered_corner_report_line
    @corner_brand_report_lines = @corner_reports.group_by {|d| d[:brand_id] }
    render :partial => '/shops/more_brand_corner_images'
  end

  def load_more_category_corner_report_lines
    @corner_reports = load_filtered_corner_report_line
    @corner_category_report_lines = @corner_reports.group_by {|d| d[:product_category_id]}
    render :partial => '/shops/more_category_corner_images'
  end

  def load_more_uploads
    @uploads = load_filter_uploads
    render :partial => '/shops/load_more_upload_images'
  end


  def load_filtered_corner_report_line
    params[:page] = params[:page].blank? ? 1 : params[:page]
    if params[:filter].present?
      search = Sunspot.search (Shop) do
        with(:city_id, params[:filter][:city_id]) if params[:filter][:city_id].present?
        with(:area_id, params[:filter][:area_id]) if params[:filter][:area_id].present?
        with(:shop_category_id, params[:filter][:shop_category_id]) if params[:filter][:shop_category_id].present?
      end
      from = params[:filter][:from].present? ? ((params[:filter][:from]).to_date).to_time : Post.first.created_at.to_date.to_time
      to = params[:filter][:to].present? ? ((params[:filter][:to]).to_date).to_time : Date.today.to_date.to_time
      @shops = search.results
      shop_ids = flatten_data(@shops, &:id)
      @posts = Post.with_shops(shop_ids).where('created_at >= ? AND created_at <= ?',from, to)
      post_ids = flatten_data(@posts,&:id)
      @reports = Report.with_posts(post_ids)
      report_ids = flatten_data(@reports,&:id)
      @corner_reports  = apply_array_pagination(ReportLine.with_reports(report_ids), params[:page])
    else
      @corner_reports =  apply_array_pagination(flatten_data(Report.with_corner_report_lines,&:report_lines).flatten, params[:page])
    end
  end

  def load_filter_uploads
    params[:page] = params[:page].blank? ? 1 : params[:page]
    if params[:filter].present?
      search = Sunspot.search (Shop) do
        with(:city_id, params[:filter][:city_id]) if params[:filter][:city_id].present?
        with(:area_id, params[:filter][:area_id]) if params[:filter][:area_id].present?
        with(:shop_category_id, params[:filter][:shop_category_id]) if params[:filter][:shop_category_id].present?
      end
      from = params[:filter][:from].present? ? ((params[:filter][:from]).to_date).to_time : Post.first.created_at.to_date.to_time
      to = params[:filter][:to].present? ? ((params[:filter][:to]).to_date).to_time : Date.today.to_date.to_time
      @shops = search.results
      shop_ids = flatten_data(@shops, &:id)
      @posts = Post.with_shops(shop_ids).where('created_at >= ? AND created_at <= ?',from, to)
      post_ids = flatten_data(@posts,&:id)
      apply_array_pagination((Upload.with_shops(shop_ids) + Upload.with_posts(post_ids)), params[:page])
    else
      Upload.page(params[:page]).per(10)
    end
  end

  def load_filter_peoples
    params[:page] = params[:page].blank? ? 1 : params[:page]
    if params[:filter].present?
      search = Sunspot.search (Shop) do
        with(:city_id, params[:filter][:city_id]) if params[:filter][:city_id].present?
        with(:area_id, params[:filter][:area_id]) if params[:filter][:area_id].present?
        with(:shop_category_id, params[:filter][:shop_category_id]) if params[:filter][:shop_category_id].present?
      end
      from = params[:filter][:from].present? ? ((params[:filter][:from]).to_date).to_time : Post.first.created_at.to_date.to_time
      to = params[:filter][:to].present? ? ((params[:filter][:to]).to_date).to_time : Date.today.to_date.to_time
      @shops = search.results
      apply_array_pagination(flatten_data(@shops, &:peoples), params[:page])
    else
      People.page(params[:page]).per(10)
    end
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
    authorize! :read, Shop
    unless params[:dealer_id].blank?
      @dealer = Dealer.find(params[:dealer_id])
    end
    @product_categories = ProductCategory.all
    @shop = Shop.where(id: params[:id]).first
    comments = @shop.comments
    @length = comments.length
    @comments = comments.last(10)
    if params[:filter].present?
      from = params[:filter][:from].present? ? ((params[:filter][:from]).to_date).to_time : Post.first.created_at.to_date.to_time
      to  = params[:filter][:to].present? ? ((params[:filter][:to]).to_date).to_time : Date.today.to_date.to_time
      @posts = @shop.posts.published_reports.flatten.select{|a| a.created_at >= from and a.created_at <= to }.flatten
    else
      @posts = @shop.posts.published_reports.flatten
    end


    @reports = @posts.collect(&:reports).flatten
    shop_report_lines = @reports.select{|a| a.report_type == "display_corner"}.collect(&:report_lines).flatten
    @brand_report_lines = shop_report_lines.group_by {|d| d[:brand_id] }
    @category_report_lines = shop_report_lines.group_by {|d| d[:product_category_id] }
    @report_lines_avatars = shop_report_lines.collect(&:avatars).flatten
    shop_upload = (Shop.find(params[:id]).uploads)
    @shop_uploads = (shop_upload + @report_lines_avatars).flatten.sort {|a,b| b[:created_at] <=> a[:created_at]}

    if current_user.user_type.name == "employee"
      reports = Post.published_reports.where(:shop_id => params[:id].to_i, :user_id => current_user.id).collect(&:reports).flatten
      @display_report = reports.select{|a| a.report_type == "display"}.collect(&:report_lines).flatten
      @sales_report   = reports.select{|a| a.report_type == "sales"}.collect(&:report_lines).flatten
      @corner_report  = reports.select{|a| a.report_type == "display_corner"}.collect(&:report_lines).flatten
      @categories = @posts.collect(&:product_category).uniq
      @brands = @categories.collect(&:brands).uniq.flatten
      @posts =  Post.where(:shop_id => params[:id].to_i, :user_id => current_user.id).sort_by{ |a| a.published ? 1 : 0 }
      @shop = Shop.find(params[:id])
    else
      @posts =  Post.where(:shop_id => params[:id].to_i).sort_by{ |a| a.published ? 1 : 0 }
      @shop = Shop.find(params[:id])
      @categories = @posts.collect(&:product_category).uniq
      @brands = @categories.collect(&:brands).uniq.flatten

app/helpers/shops_helper.rb
module ShopsHelper

  def shop_link_with_name(shop)
    link_to shop.dealer_name, shop_path(shop)
  end

  def orient_dealer(shop)
    shop.orient_dealer? ?  "<span class='label label-satgreen'>Dealer</span>".html_safe : "<span class='label label-lightred'>Non Dealer</span>".html_safe
  end

  def shop_edit_link(shop)
    link_to raw("<i class='fa fa-edit'></i>"), edit_shop_path(shop), :class => 'btn', :title => 'edit'
  end

  def shop_delete_link(shop)
    link_to raw("<i class='hi hi-off'></i>"), delete_shop_path(shop), :class => 'btn', :title => 'delete', 'data-confirm' => 'are you sure?'
  end

  def post_link_with_id(post)
    link_to post.id, "/shops/#{post.shop_id}/svr/#{post.id}"
  end

  def user_link_with_image_and_name(user)
    [user_link_with_image(user), user_link_with_name(user)].join("<br>")
  end

  def user_link_with_image(user)
    link_to raw(image_tag(user.avatar.avatar(:thumb), :class => "img-circle svr-user-image")), activities_path(:user_id => user.id), :class => "user-image-link"
  end

  def user_link_with_name(user)
    link_to user.name, activities_path(:user_id => user.id), :class => "user-name-link"
  end

  def post_action_links(post)
    '<div class="btn-group btn-group-xs">' + [post_edit_link(post),post_delete_link(post)].join(" ") + '</div>'
  end

  def post_edit_link(post)
    link_to raw("<i class='fa fa-pencil'></i>"),  "/shops/#{post.shop_id}/svrs/#{post.id}/edit", :class => 'btn btn-default', "data-toggle" => "tooltip", :title=> "Update"
  end

  def post_delete_link(post)
    link_to raw("<i class='fa fa-times'></i>"),  "/shops/#{post.shop_id}/svrs/#{post.id}/delete", "data-toggle"=>"tooltip" ,:title=>"Delete", :class => 'btn btn-danger'
  end

  def post_status_dropdown(post)
    '<div class="btn-group">
      <a class="btn btn-sm btn-success dropdown-toggle" data-toggle="dropdown" href="javascript:void(0)">Change <span class="caret"></span></a>
      <ul class="dropdown-menu text-left">
        <li class='+ published_status(post) + '>' + post_published_link(post) + '</li>
        <li class='+ un_published_status(post) + '>' + post_unpublised_link(post) + '</li>
      </ul>
    </div>'
  end

  def published_status(post)
    return 'active' if post.status == 'published'
    return ''
  end

  def un_published_status(post)
    return 'active' if post.status == 'submit'
    return ''
  end

  def post_published_link(post)
    link_to "Publish", publish_report_tasks_path(:post_id => post.id)
  end

  def post_unpublised_link(post)
    link_to "Un Publish", draft_report_tasks_path(:post_id => post.id)
  end

end

app/views/shops/_display_corner_report.html.erb
<div class="box-content nopadding" data-height="auto" data-visible="true">
  <div class="tab-content">
   <div class="tab-pane active" id="brand-data">
      <table class="table table-user table-nohead">
        <tbody>
          <% @brand_report_lines.each do |brand_id,brand_report| %>
            <% count = 0 %>
            <% brand_report.each do |line| %>
              <% line.avatars.each do |upload| %>
                <% if upload.avatar %>
                  <tr class="alpha">
                    <%if count == 0%>
                      <td class="alpha-val" colspan="8">
                        <span><%= get_brand_name(brand_id) %></span>
                      </td>
                    <% end %>
                  </tr>
                <% end %>
                <% count = count +1 %>
              <% end%>
            <%end%>
            <% brand_report.each do |line| %>
              <% line.avatars.each do |upload| %>
                <tr>
                  <% if upload.avatar %>
                    <td class ="img"><%= image_tag upload.avatar.url %></td>
                  <% else %>
                    <td class ="img"><%= image_tag "/assets/default.png"%></td>
                  <% end %>
                  <td class="user"><%= upload.avatarable.product_category.name %></td>
                  <td class="date"><%= upload.avatarable.created_at.strftime('%m,%b,%y')%></td>
                  <td><a href="<%= upload.avatar.url(:medium) %>" class='btn colorbox-image'><i class="icon-search"></i></a>
                  </td>
                </tr>
              <% end -%>
            <%end %>
          <% end-%>       
        </tbody>
      </table>    
    </div>  
    <div class="tab-pane" id="category-data">
      <table class="table table-user table-nohead">
        <tbody>
          <% @category_report_lines.each do |category,cat_report| %>
            <tr class="alpha">
              <td class="alpha-val" colspan="8">
                <span><%= get_productcategory_name(category) %></span>
              </td>
            </tr>
            <% cat_report.each do |line| %>
              <% line.avatars.each do |upload| %>
                <tr>
                  <% if upload.avatar %> 
                    <td class ="img"><%= image_tag upload.avatar.url %></td>
                  <% else %>
                    <td class ="img"><%= image_tag "/assets/default.png"%></td>
                  <% end %>
                  <td class="user"><%= upload.avatarable.brand.name %></td>
                  <td class="date"><%= upload.avatarable.created_at.strftime('%m,%b,%y')%></td>
                  <td><a href="<%= upload.avatar.url(:medium) %>" class='btn colorbox-image'><i class="icon-search"></i></a>
                  </td>
                </tr>
              <% end -%>
            <%end %>
          <% end-%>       
        </tbody>
      </table>    
    </div>
  </div>
</div> 

app/views/shops/_load_more_shops.html.erb
<% @limited_shops.each do |shop| %>
  <tr>
    <td><%= shop_link_with_name(shop) %></td>
    <td><%= orient_dealer(shop) %></td>
    <td><%= shop_edit_link(shop)  %> <%= shop_delete_link(shop) %></td>
  </tr>
<% end %>

app/views/shops/_shops.html.erb
  <div class="row">
    <div class="col-md-6">
      <%= render :partial => "/shared/map"%>
    </div>
    <% if can? :read, Shop%>
      <div class="col-md-6">
        <div class="block shops-block">
          <div class="block-title">
            <% if can? :create, Shop %>
              <div class="new-button pull-right">
               <%= link_to raw("<i class='gi gi-new_window_alt'></i> Add Shop"), new_shop_path,  :class => "btn btn-large btn-default" %>
              </div>
            <% end %>
            <h3>
              Shops
            </h3>
          </div>
          <div class="block-content dealers-data-height dearlers-list scroll-dealers-data">
            <div class="row">
              <%= form_for(:shop, :url => load_more_shops_shops_path, :html => {:method => :get, :remote => true, :class => "custom-shop-form"}) do  %>
                <div class="col-md-3">
                  <label> Search Shop </label>
                </div>
                <div class="col-md-9">
                  <%= text_field_tag "dealer_name" %>
                </div>
              <% end %>
            </div>
            <table class="table table-hover shops-table">
              <thead>
                <tr>
                  <th>Shop Name </th>
                  <th>Orient Dealer</th>
                  <th>Action</th>
                </tr>
              </thead>
              <tbody class="shop-table-body">
                <% @limited_shops.each do |shop| %>
                  <tr>
                    <td><%= shop_link_with_name(shop) %></td>
                    <td><%= orient_dealer(shop) %></td>
                    <td><%= shop_edit_link(shop)  %> <%= shop_delete_link(shop) %></td>
                  </tr>
                <% end %>
              </tbody>
            </table>

        </div>
        <div class="shop-pagination">
            <%= paginate @limited_shops, :window => 2, :left => 1, :right => 0, :remote => true, :params => { :host => request.host, :port => request.port, :controller => 'shops', :action => 'load_more_shops', :method => :get } %>
          </div>
      </div>
    <% end -%>
  </div>
  <% unless @posts.blank? %>
    <div class="row">
      <% if can? :read, Report %>
        <div class="col-md-12">
          <div class="block">
            <div class="block-title">
              <h3><strong> Sales &amp; Display  Report</strong></h3>
              <ul class="nav nav-tabs" data-toggle="tabs">
                <li class="active"><a class="brand-tab" href="#brand-display-data">Brands</a></li>
                <li><a class="category-tab" href="#category-display-data">Categories</a></li>
              </ul>
            </div>
            <div class="block-content">
              <div class="tab-content">
               <div class="tab-pane active" id="brand-display-data">
                  <%= form_for :search,:url => brand_search_svrs_path, :html => {:class => "report-search"}, :method => :post do |f| %>
                    <select name="search[product][]" multiple = "true">
                      <option value="">All</option>
                      <% @categories.each do |pc| %>
                        <% if pc.products.blank? %>
                          <option value="<%= pc.name %>"><%= pc.name %></option>
                        <% else %>
                          <optgroup label="<%= pc.name %>">
                            <% pc.products.each do |product| %>
                              <option value="<%= product.name %>"><%= product.name %></option>
                            <% end -%>
                          </optgroup>
                        <% end -%>
                      <% end -%>
                    </select>
                    <%= f.select :year , options_for_select(present_year(@reports) , Date.today.strftime('%Y') ),{} ,{:class => "col-md-3", :multiple => true, "data-selected-text-format"=>"count>5"} %>
                    <%= f.select :week , options_for_select(present_week (@reports)),{},{:class => "col-md-6" , :multiple => :true, "data-selected-text-format"=>"count>5"} %>
                  <% end -%>
                  <div class="brand-chart-data">
                    <%= render :partial => "/svrs/brand_bar", :locals => {:brands => @brands, :reports => @reports} %>
                  </div>
               </div>
               <div class="tab-pane active" id="category-display-data">
                  <%= form_for :search,:url => category_search_svrs_path, :html => {:class => "category-report-search"}, :method => :post do |f| %>
                    <select name="search[brand][]" multiple = "true">
                      <option value="">All</option>
                      <% @brands.each do |pc| %>
                        <option value="<%= pc.id %>"><%= pc.name %></option>
                      <% end -%>
                    </select>
                    <%= f.select :year , options_for_select(present_year(@reports) , Date.today.strftime('%Y') ),{} ,{:class => "col-md-3", :multiple => true, "data-selected-text-format"=>"count>5"} %>
                    <%= f.select :week , options_for_select(present_week (@reports)),{},{:class => "col-md-6" , :multiple => :true, "data-selected-text-format"=>"count>5"} %>
                  <% end -%>
                  <div class="category-chart-data">
                    <%= render :partial => "/svrs/category_bar", :locals => {:categories => @categories, :reports => @reports, :brand => nil} %>
                  </div>
               </div>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="block corner-report">
          <div class="block-title">
            <h2><strong>Display Corner Reports</strong></h2>
            <ul class="nav nav-tabs" data-toggle="tabs">
              <li class="active"><a href="#corner_brand">Brands</a></li>
              <li><a href="#corner_category">Categories</a></li>
            </ul>
          </div>
          <div class="tab-content">
            <div class="tab-pane active" id="corner_brand">
              <div class="gallery brand-content scroll-brand-corner-report brand-result" data-toggle="lightbox-gallery">
                <% @corner_brand_report_lines.each do |brand_id,brand_report| %>
                  <% unless brand_report.collect(&:avatars).flatten.blank? %>
                    <div class="row">
                      <span class="col-md-12 brand-name"><%= get_brand_name(brand_id) %></span>
                    </div>
                  <% end -%>
                  <div class="row ">
                    <% brand_report.each do |line| %>
                      <% line.avatars.each do |upload| %>
                        <div class="col-sm-4 gallery-image">
                          <% if upload.avatar %>
                          <%= link_to raw(image_tag upload.avatar.url(:small)), image_path(upload, :type => "avatar", :class => "shops") %>
                          <% else %>
                            <%= image_tag "/assets/default.png"%>
                          <% end%>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
                <div class="hide brand_corner_report_paginator">
                  <%= paginate @corner_reports, :params => {:host => request.host, :port => request.port, :controller => 'shops', :action => 'load_more_brand_corner_report_lines', :method => :get } %>
                </div>
              </div>
            </div>
            <div class="tab-pane" id="corner_category">
              <div class="gallery categroy-content scroll-category-corner-report category-result" data-toggle="lightbox-gallery">
                <% @corner_category_report_lines.each do |category,cat_report| %>
                 <% unless cat_report.collect(&:avatars).flatten.blank? %>
                    <div class="row">
                      <span class="col-md-12 brand-name"><%= get_productcategory_name(category) %></span>
                    </div>
                  <% end %>
                  <div class="row">
                    <% cat_report.each do |line| %>
                      <% line.avatars.each do |upload| %>
                        <div class="col-sm-4 gallery-image">
                          <% if upload.avatar %>
                            <%= link_to raw(image_tag upload.avatar.url(:small)), image_path(upload, :type => "avatar",:class => "shops") %>
                          <% else %>
                            <%= image_tag "/assets/default.png"%>
                          <% end%>
                        </div>
                      <% end %>
                    <% end %>
                  </div>
                <% end %>
                <div class="hide category_corner_report_paginator">
                  <%= paginate @corner_reports, :params => {:host => request.host, :port => request.port, :controller => 'shops', :action => 'load_more_category_corner_report_lines', :method => :get } %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="block image-block">
          <div class="block-title">
            <h2>Images</h2>
          </div>
          <div class="gallery upload-image-block scroll-upload-images" data-toggle="lightbox-gallery">
            <div class="row upload-content">
              <% @uploads.each do |image| %>
                <div class="col-sm-4 gallery-image">
                  <% if image.class.to_s == "Upload"%>
                    <%= link_to raw(image_tag image.upload.url(:small)), image_path(image, :type => "upload", :class => "shops") %>
                  <% else %>
                    <%= link_to raw(image_tag image.avatar.url(:small)), image_path(image, :type => "avatar", :class => "shops") %>
                  <% end %>
                </div>
              <% end %>
              <div class="hide upload_images_paginator">
                <%= paginate @uploads, :params => {:host => request.host, :port => request.port, :controller => 'shops', :action => 'load_more_uploads', :method => :get } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class = "row">
    <% if @posts.blank? %>
        <div class="col-md-6">
          <div class="block image-block">
            <div class="block-title">
              <h2>Images</h2>
            </div>
            <div class="gallery upload-image-block scroll-upload-images" data-toggle="lightbox-gallery">
              <div class="row upload-content">
                <% @uploads.each do |image| %>
                  <div class="col-sm-4 gallery-image">
                    <% if image.class.to_s == "Upload"%>
                    <%= link_to raw(image_tag image.upload.url(:small)), image_path(image, :type => "upload", :class => "shops") %>
                    <% else %>
                      <%= link_to raw(image_tag image.avatar.url(:small)), image_path(image, :type => "avatar", :class => "shops") %>
                    <% end %>
                  </div>
                <% end %>
                <div class="hide upload_images_paginator">
                  <%= paginate @uploads, :params => {:host => request.host, :port => request.port, :controller => 'shops', :action => 'load_more_uploads', :method => :get } %>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    <% if can? :read, People%>
      <div class="col-md-6">
        <div class="block dealers-image-block-height">
          <div class="block-title">
            <h3>
              <i class="icon-user">
              People </i>
            </h3>
          </div>
          <div class="block-content shop-peoples-content scroll-dealer-report" >
            <div class="people">
              <ul class="shop-peoples">
                <% @peoples.each do |people| %>
                  <li>
                    <span class="people-image"> <%= image_tag(people.avatar.avatar(:thumb)) %></span>
                    <label class="people-name"><%= people.name %> </label>
                     <span class='icon search_btn' data-id = "<%= people.id %>" ><a href="#" class='btn'><i class="fa fa-search"></i></a></span>
                  </li>
                <% end%>
                <div class="hide shop_people_paginator">
                  <%= paginate @peoples, :params => {:host => request.host, :port => request.port, :controller => 'shops', :action => 'load_more_peoples', :method => :get } %>
                </div>
              </ul>
            </div>
          </div>
        </div>
      </div>
    <%end -%>
  </div>