config/routes.rb
Orient::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :user_types

  resources :home do
    collection do
      get 'toggle_email_notifications'
    end
  end

  match '/home_activities' => "home#activities", :method => :get
  match '/subscriber_activities' => "home#subscriber_activities", :method => :get
  match '/notifications' => "home#notifications", :method => :get
  match '/user_activities' => "home#user_activities", :method => :get

  resources :roles

  resources :comments do
    member do
      get 'load_more_comments'
    end
  end

  resources :search

  resources :areas do
    collection do
      get "search"
    end
  end

  resources :announcements do
    collection do
      get 'update_user_status'
    end
  end

  resources :product_categories do
    resources :svrs
  end

  resources :activities do
    member do
      get 'destroy_subscriber'
    end
    collection do
      get 'update_activity'
      post 'create_subscriber'
    end
  end

  resources :dealers do
   resources :images
   resources :shops
    member do
      get 'gallery'
      get 'showmodal'
      get 'get_info'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'showgallery'
      get 'area_field'
      get 'load_more_peoples'
      get 'load_more_dealers'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end

  end

  resources :brands do
    resources :svrs
  end

  resources :products do
    resources :svrs
  end

  resources :shop_categories do
    resources :shops
  end

  resources :cities do
    resources :shops
  end

  resources :locations do
    resources :shops
  end

  resources :images do
    member do
      post 'create_comment'
      get 'view_more_comments'
    end
  end

  resources :shops do
    resources :uploads
    resources :images
    resources :svrs do
      member do
        get "delete"
        get "comments"
        get "view_more_comments"
        post 'create_comment'
      end
    end

    member do
      get 'delete'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'area_field'
      get 'people_field'
      get 'load_more_peoples'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end
  end

  resources :uploads do
   member do
    post 'create_comment'
   end
  end

  resources :tasks do
    member do
      post 'change_status'
    end
    collection do
      get 'publish_report'
      get 'unpublish_report'
      get 'draft_report'
      get 'submit_report'
    end
  end

  resources :svrs do
    collection do
      post 'brand_search'
      post 'category_search'
      get  'file_field'
      get 'upload_field'
    end
  end

  match 'shops/:shop_id/svr/:id' => 'svrs#show', as: 'show'

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	params[:page] = params[:page].blank? ? 1 : params[:page]
    #@subscriber_activities = Kaminari.paginate_array(current_user.subscribers.collect(&:activities).flatten.sort{|a, b| b[:created_at] <=> a[:created_at]}).page(params[:page]).per(5)
    @user_activities = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.id, owner_type: "User") if current_user.user_employee?
    @subscriber_activities = current_user.subscribers.collect(&:activities).flatten.sort{|a, b| b[:created_at] <=> a[:created_at]}
  end

  def activities
  	params[:page] = params[:page].blank? ? 1 : params[:page]
  	@activities = PublicActivity::Activity.order("created_at desc").where(owner_id: current_user.id, owner_type: "User").page(params[:page]).per(5)
  	render :partial => '/home/activities', :layout => false
  end

  def notifications
  	 params[:page] = params[:page].blank? ? 1 : params[:page]
     @notifications_count = current_user.subscribers.collect(&:notifications).flatten.sort{|a, b| b[:created_at] <=> a[:created_at]}.count
     @notifications = Kaminari.paginate_array(current_user.subscribers.collect(&:notifications).flatten.sort{|a, b| b[:created_at] <=> a[:created_at]}).page(params[:page]).per(5)
     render :partial => '/home/notifications', :layout => false
  end

  def subscriber_activities
  	params[:page] = params[:page].blank? ? 1 : params[:page]
    @subscriber_activities = Kaminari.paginate_array(current_user.subscribers.collect(&:activities).flatten.sort{|a, b| b[:created_at] <=> a[:created_at]}).page(params[:page]).per(5)
    render :partial => '/home/subscriber_activities', :layout => false
  end

  def user_activities
    params[:page] = params[:page].blank? ? 1 : params[:page]
    user = User.find(params[:user_id])
    @user_activities = PublicActivity::Activity.order("created_at desc").where(owner_id: user.id, owner_type: "User").page(params[:page]).per(5)
    render :partial => '/home/user_activities', :layout => false
  end

  def toggle_email_notifications
    user = current_user
    user.send_notification  =  user.send_notification? ? false : true
    user.save
    flash[:notice] = "Email subscription updated"
    redirect_to :back
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_activities.html.erb
<% @activities.each do |activity| %>
  <div class="alert alert-info alert-alt my_activities">
    <small><%= activity.created_at.strftime("%B %d, %Y - %I:%M %p")%></small><br>
     <i class="fa fa-arrow-up fa-fw"></i>
     <% if activity.message.blank? %>
      You <%= render_activity activity %>
    <% else %>
      <%= render :partial => "/shared/post" , :locals => {:@activity => activity } %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
	$(document).ready(function(){
		$('.activities .pagination').replaceWith("<%= j paginate @activities, :params => {:host => request.host, :port => request.port, :controller => 'home', :action => 'activities', :method => :get } %>");
	});
</script>

app/views/home/_notifications.html.erb
<% @notifications.each do |notification|%>
  <div class="alert  alert-info alert-alt my-notification notification" data-notification="<%= notification.id %>">
    <small><%= notification.created_at.strftime("%B, %d")%></small><br>
    <i class="fa fa-arrow-up fa-fw"></i><%= notification.owner.name %>  <%= render_activity notification %>
  </div>
<% end %>

<script type="text/javascript">
	$(document).ready(function(){

		$('.pager_notification .pagination').replaceWith("<%= j paginate @notifications, :params => {:host => request.host, :port => request.port, :controller => 'home', :action => 'notifications', :method => :get} %>");

		$(".notification").click(function(){
	    id = $(this).data("notification");
	    count = $(".notification-count").text();
	    $(this).remove();
	    $.ajax ({
	      url:  '/activities/update_activity',
	      data: {id: id },
	      success: function(data)
	      {

	        if(count>0)
	          $(".notification-count").text(count-1);
	      }
	    });
		});
	});
</script>

app/views/home/_subscriber_activities.html.erb
<% @subscriber_activities .each do |activity| %>
	<li class="media user-activity subscribe-activity">
    <% user = User.find(activity.owner.id) %>
		<a href="<%= activities_path(:user_id => user.id) %>" class="pull-left user-link-small">
      <%= image_tag(user.avatar.avatar(:thumb), :class => "img-circle user-image-small") %>
    </a>
    <div class="media-body">
      <p class="push-bit">
        <span class="text-muted pull-right">
          <small><%= activity.created_at.strftime("%B %d, %Y - %I:%M %p")%></small>
          <span class="text-danger" data-toggle="tooltip" title="From Web"><i class="fa fa-globe"></i></span>
        </span>
        <strong><%=link_to activity.owner.name, activities_path(:user_id => activity.owner.id) if activity.owner %> <%= render_activity activity %> </strong>
      </p>
    </div>
	</li>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    $('.subscribe .pagination').replaceWith("<%= j paginate @subscriber_activities, :params => {:host => request.host, :port => request.port, :controller => 'home', :action => 'subscriber_activities', :method => :get } %>");
  });
</script>

app/views/home/_user_activities.html.erb
<% @user_activities.each do |activity| %>
	<li class="media user-activity">
    <% user = User.find(activity.owner.id) %>
    <%=link_to raw(image_tag(user.avatar.avatar(:thumb), :class => "img-circle user-image-small")), activities_path(:user_id => user.id),:class => "pull-left user-link-small" %>
    <div class="media-body">
      <p class="push-bit">
        <span class="text-muted pull-right">
          <small><%= activity.created_at.strftime("%B %d, %Y - %I:%M %p")%></small>
          <span class="text-danger" data-toggle="tooltip" title="From Web"><i class="fa fa-globe"></i></span>
        </span>
        <strong><%=link_to activity.owner.name, activities_path(:user_id => user.id) if activity.owner %> <%= render_activity activity %> </strong>
      </p>
    </div>
  </li>
<% end %>


<script type="text/javascript">
  $(document).ready(function(){
    $('.user_activities .pagination').replaceWith("<%= j paginate @user_activities, :params => {:host => request.host, :port => request.port, :controller => 'home', :action => 'notifications', :method => :get, :user_id => @user_activities.first.owner.id } %>");
  });
</script>

app/views/home/index.html.erb
<%= render :partial => "/layouts/user_header" %>
<% unless current_user.user_employee? %>
  <div class="row">
  	<!-- First Column -->
      <div class="col-md-6 col-lg-7">
   			<% unless @subscriber_activities.blank? %>
  	 			<!-- Newsfeed Block -->
  	 			<div class="block">

  	 				<!-- Newsfeed Title -->
  	        <div class="block-title">
  	          <h2><strong>Subscribers Actiivities</strong></h2>
  	        </div>
  	        <!-- END Newsfeed Title -->

  	        <!-- Newsfeed Content -->
  	        <div class="block-content-full">
              <% unless @subscriber_activities.blank? %>
    	        	<ul class="media-list media-feed media-feed-hover" data-domain = "<%= APP_CONFIG["domain"] %>">
    	        		<% @subscriber_activities .each do |activity| %>
                    <%= render :partial=> "/shared/activity_with_comments", :locals => {:activity => activity, :user => activity.owner } %>
    	        		<% end %>
                   <!-- <div class="subscribe hide">
                    <%#= paginate @subscriber_activities, :params => {:host => request.host, :port => request.port, :controller => 'home', :action => 'subscriber_activities', :method => :get } %>
                  </div> -->
    	        	</ul>
              <% end %>
  	        </div>
  	        <!-- END Newsfeed Content -->
  	 			</div>
  	 			<!-- END feed Block -->
  	 		<% end %>
   		</div>
   		<!-- END First Column -->

   		<!-- Second Column -->
   		<div class="col-md-6 col-lg-5">
   			<!-- Friends Block -->
   			<div class="block">
          <!-- Friends Title -->
          <div class="block-title">
            <div class="block-options pull-right">
              <% if current_user.send_notification? %>
                <%= link_to raw('<i class="fa fa-power-off"></i>'), toggle_email_notifications_home_index_path, :class => "btn btn-sm btn-danger" , "data-toggle" => "tooltip", :title => "", "data-original-title" => "Turn off email subscriptions" %>
              <% else %>
                <%= link_to raw('<i class="fa fa fa-power-off"></i>'), toggle_email_notifications_home_index_path, :class => "btn btn-sm btn-success" , "data-toggle" => "tooltip", :title => "", "data-original-title" => "Turn on email subscriptions" %>
              <% end %>
          </div>
            <h2><strong>Subscribers </strong> <small> <a href="javascript:void(0)">(<%= current_user.subscribers.count %>)</a></small></h2>

          </div>
          <!-- END Friends Title -->

          <!-- Friends Content -->
          <div class="row text-center">
            <% current_user.subscribers.each do |sub| %>
            	<% user = User.find(sub.subscribe_id) %>
              <div class="col-xs-4 col-sm-3 col-lg-2 block-section">
                <a href="<%= activities_path(:user_id => user.id) %>">
                	<% unless user.avatar.blank? %>
                  	<%= image_tag(user.avatar.avatar(:thumb), :class => "img-circle subscribed-image" , "data-toggle" => "tooltip", :title => user.name )%>
                  <% end %>
                </a>
              </div>
            <% end %>
          </div>
        <!-- END Friends Content -->
        </div>
  	    <!-- END Friends Block -->
   		</div>
   		<!-- END Second Column -->
  </div>
<% else %>
  <div class="row">
    <!-- First Column -->
    <div class="col-md-6 col-lg-7">
      <% unless @activities.blank? %>
        <!-- Newsfeed Block -->
        <div class="block">

          <!-- Newsfeed Title -->
          <div class="block-title">
            <h2><strong>Your Activites</strong></h2>
          </div>
          <!-- END Newsfeed Title -->

          <!-- Newsfeed Content -->
          <div class="block-content-full">
            <ul class="media-list media-feed media-feed-hover">
              <% @user_activities.each do |activity| %>
                <%= render :partial=> "/shared/activity_with_comments", :locals => {:activity => activity, :user => activity.owner } %>
              <% end %>

            </ul>
          </div>
          <!-- END Newsfeed Content -->
        </div>
        <!-- END feed Block -->
      <% end %>
    </div>
    <!-- END First Column -->
  </div>
<% end %>