config/routes.rb
Orient::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :user_types

  resources :home do
    collection do
      get 'toggle_email_notifications'
    end
  end

  match '/home_activities' => "home#activities", :method => :get
  match '/subscriber_activities' => "home#subscriber_activities", :method => :get
  match '/notifications' => "home#notifications", :method => :get
  match '/user_activities' => "home#user_activities", :method => :get

  resources :roles

  resources :comments do
    member do
      get 'load_more_comments'
    end
  end

  resources :search

  resources :areas do
    collection do
      get "search"
    end
  end

  resources :announcements do
    collection do
      get 'update_user_status'
    end
  end

  resources :product_categories do
    resources :svrs
  end

  resources :activities do
    member do
      get 'destroy_subscriber'
    end
    collection do
      get 'update_activity'
      post 'create_subscriber'
    end
  end

  resources :dealers do
   resources :images
   resources :shops
    member do
      get 'gallery'
      get 'showmodal'
      get 'get_info'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'showgallery'
      get 'area_field'
      get 'load_more_peoples'
      get 'load_more_dealers'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end

  end

  resources :brands do
    resources :svrs
  end

  resources :products do
    resources :svrs
  end

  resources :shop_categories do
    resources :shops
  end

  resources :cities do
    resources :shops
  end

  resources :locations do
    resources :shops
  end

  resources :images do
    member do
      post 'create_comment'
      get 'view_more_comments'
    end
  end

  resources :shops do
    resources :uploads
    resources :images
    resources :svrs do
      member do
        get "delete"
        get "comments"
        get "view_more_comments"
        post 'create_comment'
      end
    end

    member do
      get 'delete'
      get 'view_more_comments'
      post 'create_comment'
    end
    collection do
      get 'area_field'
      get 'people_field'
      get 'load_more_peoples'
      get 'load_more_brand_corner_report_lines'
      get 'load_more_category_corner_report_lines'
      get 'load_more_uploads'
      get 'load_more_shops'
    end
  end

  resources :uploads do
   member do
    post 'create_comment'
   end
  end

  resources :tasks do
    member do
      post 'change_status'
    end
    collection do
      get 'publish_report'
      get 'unpublish_report'
      get 'draft_report'
      get 'submit_report'
    end
  end

  resources :svrs do
    collection do
      post 'brand_search'
      post 'category_search'
      get  'file_field'
      get 'upload_field'
    end
  end

  match 'shops/:shop_id/svr/:id' => 'svrs#show', as: 'show'

  devise_for :users, :controllers => {:registrations => "registrations"}

  root :to => 'home#index'

end

app/models/report.rb
class Report < ActiveRecord::Base
  include PublicActivity::Common
  has_many :report_lines, :dependent => :destroy
  has_many :products, :through => :report_lines

  belongs_to :shop
  belongs_to :user

  belongs_to :post

  attr_accessible :data, :week, :year, :report_type, :user_id, :shop_id, :report_lines_attributes, :post_id

  accepts_nested_attributes_for :report_lines

  scope :post_reports, lambda { |id | where(:post_id => id) }
  scope :with_corner_report_lines,  includes([:report_lines, :post]).where("posts.published =? AND reports.report_type =? AND report_lines.data =?", true,'display_corner',true)
  scope :with_posts, lambda { |id | where(:post_id => id) }
  scope :corner_reports, lambda { |id | where('id =? AND report_type =?', id, "display_corner") }

  validates_presence_of :report_type, :user_id
  validates_associated :report_lines

  def self.reports_of(value)
    Report.where(:report_type => value)
  end

  def self.brand_sales(reports,brand_id)
    reports.select{|key| key.report_type=="sales"}.collect(&:report_lines).flatten.select{|key| key.brand_id == brand_id }.collect(&:data).reject {|r|r.nil?}.sum
  end

  def self.brand_display(reports,brand_id)
    count = reports.select{|key| key.report_type=="display"}.collect(&:report_lines).flatten.select{|key| key.brand_id == brand_id }.collect(&:data).reject {|r|r.nil?}.count
    sum = reports.select{|key| key.report_type=="display"}.collect(&:report_lines).flatten.select{|key| key.brand_id == brand_id }.collect(&:data).reject {|r|r.nil?}.sum
    if sum == 0
      0
    else
      (sum/count)
    end
  end

  def self.brand_corner(reports,brand_id)
    reports.select{|key| key.report_type=="display_corner"}.collect(&:report_lines).flatten.select{|key| key.brand_id == brand_id }.collect(&:data).reject {|r|r.nil?}.sum
  end

  def self.category_sales(reports,category_id,brand)
    if brand.nil?
      sum = reports.select{|key| key.report_type=="sales"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id }.collect(&:data).reject {|r|r.nil?}.sum
      count = reports.select{|key| key.report_type=="sales"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id }.collect(&:data).reject {|r|r.nil?}.count
    else
      sum = reports.select{|key| key.report_type=="sales"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id && key.brand_id == brand }.collect(&:data).reject {|r|r.nil?}.sum
      count = reports.select{|key| key.report_type=="sales"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id && key.brand_id == brand }.collect(&:data).reject {|r|r.nil?}.count
    end
    if sum == 0
      0
    else
      (sum/count)
    end
  end

  def self.category_display(reports,category_id,brand)
    if brand.blank?
      reports.select{|key| key.report_type=="display"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id }.collect(&:data).reject {|r|r.nil?}.sum
    else
      reports.select{|key| key.report_type=="display"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id && brand.include?(key.brand_id)}.collect(&:data).reject {|r|r.nil?}.sum
    end
  end

  def self.category_corner(reports,category_id,brand)
    if brand.nil?
      reports.select{|key| key.report_type=="display_corner"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id }.collect(&:data).reject {|r|r.nil?}.sum
    else
      reports.select{|key| key.report_type=="display_corner"}.collect(&:report_lines).flatten.select{|key| key.product_category_id == category_id && key.brand_id == brand }.collect(&:data).reject {|r|r.nil?}.sum
    end
  end

  def report_view(brand_id)
    self.report_lines.flatten.select{|key| key.brand_id == brand_id }.collect(&:data).reject {|r|r.nil?}.sum
  end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def json_data(data)
    ActiveSupport::JSON.decode(data)
  end

end

app/views/reports/edit.html.erb
<div class="container-fluid">
  <div class="page-header">
    <div class="pull-left">
      <h1>Edit report </h1>
    </div>
  </div>
  <div class="row-fluid">
    <div class="span12">
      <div class="box box-color box-bordered">
        <div class="box-title">
          <h3>
            <i class="icon-magic"></i>
            Edit Report
          </h3>
        </div>
        <div class="box-content scrollable">
          <%= form_for @post , :url => "/shops/#{@shop.id}/reports/#{@post.id}" , :html => { :class => 'form-horizontal form-validate', :multipart => true } do |f| %>
            <%= f.hidden_field :shop_id %>
            <%= f.hidden_field :user_id %>
            <%= f.hidden_field :product_category_id %>
            <%= f.hidden_field :dealer_id %>
            <div class='row-fluid'>
              <div class= "span6" >
                <%= f.label :year ,"Year", :class => 'control-label' %>  
                <%= f.select :year , options_for_select( (2000..2020).to_a , @post.reports.first.year) %>
              </div>
              <div class ="span6">
                <%= f.label :week ,"Week number", :class => 'control-label' %> 
                <%= f.select :week , options_for_select(year_weeks, @post.reports.first.week) %>
              </div>
            </div>
            <%= f.fields_for :reports do |report| %>
              <% if report.object.report_type == 'display' or report.object.report_type == 'sales' %>
                <% type=report.object.report_type %>
                <div class="step">
                  <div class="single-step">
                    <span class="circle">
                      <span class="active"></span>
                    </span>
                    <span class="description">
                      <h3> <%= report.object.report_type.capitalize %> Information </h3> <hr />
                    </span>
                  </div>
                </div>
                <div class="step-forms ">
                  <%= report.hidden_field :report_type %>
                  <%= report.hidden_field :shop_id %>
                  <%= report.hidden_field :user_id %>
                  <div class="step-forms ">
                    <%= report.fields_for :report_lines do |report_line| %>
                      <div class="control-group">
                        <% brand= Brand.find report_line.object.brand_id %>
                        <%= report_line.hidden_field :product_category_id %>
                        <%= report_line.hidden_field :product_id %>
                        <%= report_line.hidden_field :brand_id %>
                        <%= report_line.label :data,"#{brand.name} #{type}", :class => 'control-label' %>
                        <%= report_line.text_field :data , :class => "input-xlarge required number"%>
                      </div>
                    <% end -%>
                  </div>
                </div>
              <% else %>
                <% type=report.object.report_type %>
                <div class="step">
                  <div class="single-step">
                    <span class="circle">
                      <span class="active"></span>
                    </span>
                    <span class="description">
                      <h3> <%= report.object.report_type.capitalize %> Information </h3> <hr />
                    </span>
                  </div>
                </div>
                <div class="step-forms ">
                  <%= report.hidden_field :report_type %>
                  <%= report.hidden_field :shop_id %>
                  <%= report.hidden_field :user_id %>
                  <div class="step-forms ">
                    <%  index = 0 %>
                    <%= report.fields_for :report_lines do |report_line| %>
                      
                      <% brand= Brand.find report_line.object.brand_id %>
                      <%= report_line.hidden_field :product_category_id %>
                      <%= report_line.hidden_field :product_id %>
                      <%= report_line.hidden_field :brand_id %>
                      <div class="control-group">
                        <%= report_line.label :data,"#{brand.name.capitalize} #{type.capitalize}", :class => 'control-label' %>
                        <div class="controls">
                          <div class = "radio-controls-edit required" remote ="true">
                            <label class="radio" data-index= "<%= index %>">
                              <%= report_line.radio_button :data, "1" ,:checked => "checked" %>Yes
                            </label>
                            <label class="radio" data-index= "<%= index %>" data-id = "<%= report_line.object.id%>">
                              <%= report_line.radio_button :data, "0" %>No
                            </label>
                            
                            <div class="parent-avatar-field">
                              <%= report_line.fields_for :avatars do |avatar| %>
                                  <div class="image-field">      
                                    <%= image_tag(avatar.object.avatar(:thumb)) %>
                                    <%= avatar.label "Change Image"  %>
                                    <div class="avatar-fields">
                                      <%= avatar.file_field :avatar  %>
                                    </div>
                                  </div>  
                              <% end %>
                              <div class="add-more-avatar"></div>

                              <%= link_to "Add More", "#", :remote => :true , :class => "edit_add_more_link #{"hide" unless !report_line.object.avatars.blank?} ", :data => {:index => index }  %> 
                            </div>
                          </div>

                        </div>
                      </div>
                      <% index += 1 %>
                    <% end -%>
                  </div>
                </div>
              <% end -%>
            <% end -%>
            <div class="form-actions">
              <input type="reset" class="btn" value="Back" id="back">
              <input type="submit" class="btn btn-primary" value="Submit" id="next">
            </div>
          <% end -%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/show.html.erb
<h2>Shop visit report</h2>
<hr>
<div class='row-fluid'>
  <div class='span4'>
    <table class='table table-bordered table-nomargin table-condensed'>
      <thead></thead>
        <tr>
          <td><strong>Week: </strong></td>
          <td><%= @report.week %></td>
        </tr>
        <tr>
          <td><strong>Date Range: </strong></td>
          <td><%= year_weeks[@report.week-1][0].split(' - ')[1] unless @report.week.blank? %></td>
        </tr>
        <tr>
          <td><strong>Submitted on: </strong></td>
          <td><%= @post.created_at.strftime('%d %B, %Y') %></td>
        </tr>
        <tr>
          <td><strong>Status: </strong></td>
          <td><%= @post.published ? 'Published' : 'Draft' %></td>
        </tr>
    </table>
  </div>
  <div class='span3 offset1'>
    <table class='table table-bordered table-nomargin table-condensed'>
      <thead></thead>
      <tr>
        <td><strong>Shop: </strong></td>
        <td><%= link_to @post.shop.dealer_name, shop_path(@post.shop) %></td>
      </tr>
      <tr>
        <td><strong>Dealer: </strong></td>
        <td><%= link_to @post.dealer.name, dealer_path(@post.dealer) %></td>
      </tr>
      <tr>
        <td><strong>City: </strong></td>
        <td><%= @post.shop.location.city.name %></td>
      </tr>
      <tr>
        <td><strong>Product Category: </strong></td>
        <td><%= @display_report.first.product_category.name %></td>
      </tr>
    </table>
  </div>
  <div class='span3 offset1'>
    <table class='table table-bordered table-nomargin table-condensed'>
      <thead></thead>
      <tr>
        <td><strong>Submitted by: </strong></td>
        <td><%= link_to @report.user.name, activities_path(:user_id => @report.user_id) %></td>
      </tr>
      <tr>
        <td><strong>Assigned by: </strong></td>
        <td><%= link_to(@post.task.try(&:parent), activities_path(:user_id => @post.task.try(&:assigned_by))) %></td>
      </tr>
      <tr>
        <td><strong>Approved by: </strong></td>
        <td><%= link_to User.find(@post.approved_id).name, activities_path(:user_id => @post.approved_id) unless @post.approved_id.blank? %></td>
      </tr>
    </table>
  </div>
</div>
<hr>
<div class="row-fluid">
  <div class="span12">
    <div class="box box-color box-bordered">
      <div class="box-title">
        <h3>
          <i class="icon-bar-chart"></i>
          Display
        </h3>
        <div class="actions">
          <a href="#" class="btn btn-mini content-slideUp"><i class="icon-angle-down"></i></a>
        </div>
      </div>
      <div class="box-content nonpadding" data-height ='auto' >
        <div class='row-fluid'>
          <div class="span3">
            <table class="table table-hover table-nomargin table-bordered dataTable-fixedcolumn dataTable-scroll-x dataTable-scroll-y table-condensed">
          <thead>
            <tr>
              <th>Brand</th>
              <th>Quantity</th>
            <tr/>
          </thead>
          <tbody>
            <% @display_report.each do |report| %>
            <tr>
              <td><strong><%= report.brand.name %></strong></td>
              <td><%= report.data.to_i %></td>
            </tr>
            <% end -%>
          </tbody>
            </table>
          </div>
          <div class='span9'>
            <%= render :partial => "/reports/bar", :locals => {:brands => Brand.all, :reports => @reports, :type => "display_data"} %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="box box-color box-bordered">
      <div class="box-title">
        <h3>
          <i class="icon-bar-chart"></i>
          Sales
        </h3>
        <div class="actions">
          <a href="#" class="btn btn-mini content-slideUp"><i class="icon-angle-down"></i></a>
        </div>
      </div>
      <div class="box-content nonpadding" data-height ='auto' >
        <div class='row-fluid'>
          <div class="span3">
            <table class="table table-hover table-nomargin table-bordered dataTable-fixedcolumn dataTable-scroll-x dataTable-scroll-y table-condensed">
          <thead>
            <tr>
              <th>Brand</th>
              <th>Quantity</th>
            <tr/>
          </thead>
          <tbody>
            <% @sales_report.each do |report| %>
            <tr>
              <td><strong><%= report.brand.name %></strong></td>
              <td><%= report.data.to_i %></td>
            </tr>
            <% end -%>
          </tbody>
            </table>
          </div>
          <div class='span9'>
            <%= render :partial => "/reports/bar", :locals => {:brands => Brand.all, :reports => @reports, :type => "sales_data"} %>
          </div>
        </div>
      </div>
    </div>
  </div> 
</div>
<div class="row-fluid">
  <div class="span12">
    <div class="box box-color box-bordered">
      <div class="box-title">
        <h3>
          <i class="icon-bar-chart">
          Display Corner Report </i>
        </h3>
        <div class="actions">
          <a href="#" class="btn btn-mini content-slideUp"><i class="icon-angle-down"></i></a>
        </div>
        <ul class="tabs">
          <li class="active">
            <a href="#brand-data" data-toggle="tab">Brand Data</a>
          </li>
          <li class="">
            <a href="#category-data" data-toggle="tab">Category Data</a>
          </li>
        </ul>
      </div>
      <%= render :partial => "shops/display_corner_report"%>
    </div>
  </div>
</div>    